apiVersion: v1
data:
  ws: jNlqkDtUYLuLTpYDnYzA+Kdpv+NCq7C+xEdDz7KSzXp0GQO2HiKYjxp25l4s+Man.Yk8sZou9DZwaEFJD.y9yshnFXSmIhatOWPXDSXw==
kind: Secret
metadata:
  name: ethstats-secrets
  namespace: pow
type: Opaque
# kubesec:v:3
# kubesec:gcp:projects/prysmaticlabs/locations/global/keyRings/prysmatic-k8s-secrets/cryptoKeys/testkey:CiQAaKPz55imKn09+ay5Fipt8Ejsa0fl9RAiDUwIB8QjWJniNfESSQD23sIsO81pJ6gDAzc7733PGECLQ+ftcvluf41iLs5GUBBHrk6ziqmtDmfiTzc9E2YDuXYwAU4EejVjXoIHMESywm9EvetOEt4=
# kubesec:mac:d9CgWefmhKBZvpQK.J+4B37sy8PsDSoVV2P7X9g==
