kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: public-node
  namespace: pow
  labels:
    universe: geth
    component: public-rpc-node
spec:
  replicas: 2
  serviceName: "public-rpc-node"
  selector: 
    matchLabels:
      universe: geth
      component: public-rpc-node
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        universe: geth
        component: public-rpc-node
    spec:
      priorityClassName: production-priority
      containers:
        - name: prober
          image: gcr.io/prysmaticlabs/prysm/geth-prober 
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
        - name: node
          image: ethereum/client-go:alltools-stable
          ports: 
           - containerPort: 8545
             name: rpc
           - containerPort: 8546
             name: ws
           - containerPort: 30303
             name: discovery-tcp
             protocol: TCP
           - containerPort: 30303
             name: discovery-udp
             protocol: UDP
          # Use /bin/sh -c to execute geth so that we have access to HOSTNAME in 
          # the command arguments.
          # https://github.com/kubernetes/kubernetes/issues/57726
          command:
            - "/bin/sh"
            - "-c"
            - >
              geth
              --networkid=5
              --ethstats=💎prylabs-$HOSTNAME:$(ETHSTATS_WS_SECRET)@wss://stats.goerli.net
              --rpc
              --rpcaddr=0.0.0.0
              --rpccorsdomain="*"
              --rpcvhosts="*"
              --ws
              --wsaddr=0.0.0.0
              --wsorigins="*"
              --datadir=/ethereum
              --keystore=/keystore
              --debug
              --verbosity=3
              --nousb
              --lightserv=50
              --metrics
          volumeMounts:
            - name: chaindata
              mountPath: /ethereum
          env:
            - name: ETHSTATS_WS_SECRET
              valueFrom:
                secretKeyRef:
                  name: ethstats-secrets
                  key: ws
          resources:
            requests:
              memory: "1000Mi"
              cpu: "200m"
            limits:
              memory: "1200Mi"
              cpu: "200m"
      initContainers:
        - name: copy-staticnodes
          image: busybox
          command: ["cp", "/data/static-nodes.json", "/ethereum/static-nodes.json"] 
          volumeMounts:
            - name: networkdata
              mountPath: "/data"
              readOnly: true
            - name: chaindata
              mountPath: "/ethereum"
        - name: init-genesis
          image: ethereum/client-go:alltools-stable
          command: ["geth"]
          args: ["--datadir=/ethereum", "init", "/data/genesis.json"]
          volumeMounts:
            - name: networkdata
              mountPath: "/data"
              readOnly: true
            - name: chaindata
              mountPath: "/ethereum"
      volumes:
        - name: networkdata
          configMap: 
            name: goerli
            items:
              - key: genesis
                path: genesis.json
              - key: staticnodes
                path: static-nodes.json
  volumeClaimTemplates:
    - metadata:
        name: chaindata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Gi
